"""empty message

Revision ID: abeaae17c188
Revises: b1eb352eca3c
Create Date: 2026-05-17 21:25:13.642141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'abeaae17c188'
down_revision: Union[str, Sequence[str], None] = 'b1eb352eca3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('ativo', sa.Boolean(), nullable=False))
    op.add_column('ofertador', sa.Column('ativo', sa.Boolean(), nullable=False))
    op.add_column('veiculo', sa.Column('ativo', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('veiculo', 'ativo')
    op.drop_column('ofertador', 'ativo')
    op.drop_column('cliente', 'ativo')
    # ### end Alembic commands ###