"""Initial

Revision ID: f59c537d44cc
Revises: 
Create Date: 2026-05-17 16:43:08.900464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f59c537d44cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('CPF', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ofertador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('CNPJ', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('fk_ofertador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_ofertador'], ['ofertador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aluguel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fk_cliente', sa.Integer(), nullable=False),
    sa.Column('fk_veiculo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['fk_veiculo'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clienteveiculo',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('cliente_id', 'veiculo_id')
    )
    op.create_table('documento',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fk_veiculo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_veiculo'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('metodo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fk_aluguel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_aluguel'], ['aluguel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fk_aluguel')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamento')
    op.drop_table('documento')
    op.drop_table('clienteveiculo')
    op.drop_table('aluguel')
    op.drop_table('veiculo')
    op.drop_table('ofertador')
    op.drop_table('cliente')
    # ### end Alembic commands ###